In [75]:
import numpy as np
from scipy import *
from scipy.linalg import lu

### Solve the following system of equations using LU Decomposition method:
#### Find L and U by hand.
#### Confirm that A=LU then solve.
- Ex1. 𝟐𝒙+𝟓𝒚=𝟐𝟏, 𝒙+𝟐𝒚=𝟖.
- Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒

#### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

### Note (when using scipy):
- In the second system of equations We can see the <b>L and U</b> we get are different from the ones we got by hand. 
- You will also see there is a permutation matrix <b>P</b> that returned by the <b>lu function</b>. 
- This permutation matrix record how do we change the order of the equations for easier calculation purposes (for example, if first element in first row is zero, it can not be the pivot equation, since you can not turn the first elements in other rows to zero. Therefore, we need to switch the order of the equations to get a new pivot equation). 
- If you multiply <b>P with A</b>, you will see that this permutation matrix effect.
- You will need to arrange the ouput based on the new matrix <b>A</b> achieved by <b>LU</b> multiplication in order to correctly solve the system of equations.

In [2]:
A = [[2,5],
     [1,2]]

L = [[1,0],
    [0.5,1]]

U = [[2,5],
    [0,-0.5]]

Y = [21,8]


In [3]:
L_inv = np.linalg.inv(L)
L_inv

array([[ 1. ,  0. ],
       [-0.5,  1. ]])

In [4]:
M = np.dot(L_inv,Y)
M

array([21. , -2.5])

In [5]:
U_inv = np.linalg.inv(U)
U_inv

array([[ 0.5,  5. ],
       [-0. , -2. ]])

In [6]:
X = np.dot(U_inv,M)
X

array([-2.,  5.])

In [ ]:
####################################

In [7]:
P,L,U = lu(A)
print(P)
print("--------------------------------------------")
print(L)
print("--------------------------------------------")
print(U)
print("--------------------------------------------")
print(np.dot(L,U))

[[1. 0.]
 [0. 1.]]
--------------------------------------------
[[1.  0. ]
 [0.5 1. ]]
--------------------------------------------
[[ 2.   5. ]
 [ 0.  -0.5]]
--------------------------------------------
[[2. 5.]
 [1. 2.]]


In [8]:
L_inv = np.linalg.inv(L)
L_inv

array([[ 1. ,  0. ],
       [-0.5,  1. ]])

In [9]:
M = np.dot(L_inv,Y)
M

array([21. , -2.5])

In [10]:
U_inv = np.linalg.inv(U)
U_inv

array([[ 0.5,  5. ],
       [-0. , -2. ]])

In [11]:
X = np.dot(U_inv,M)
X

array([-2.,  5.])

In [ ]:
###############################################

In [12]:
A = [[ 1,1,1],
    [ 4,3,-1],
    [ 3,5,3]]

L = [[ 1,0,0],
    [ 4,1,0],
    [ 3,-2,1]]

U = [[ 1,1,1],
    [ 0,-1,-5],
    [ 0,0,-10]]

Y = [1,6,4]


In [13]:
L_inv = np.linalg.inv(L)
L_inv

array([[  1.,   0.,   0.],
       [ -4.,   1.,  -0.],
       [-11.,   2.,   1.]])

In [14]:
M = np.dot(L_inv,Y)
M

array([1., 2., 5.])

In [15]:
U_inv = np.linalg.inv(U)
U_inv

array([[ 1. ,  1. , -0.4],
       [-0. , -1. ,  0.5],
       [-0. , -0. , -0.1]])

In [16]:
X = np.dot(U_inv,M)
X

array([ 1. ,  0.5, -0.5])

In [17]:
#####################################3

In [23]:
P,L,U = lu(A)
print(P)
print("--------------------------------------------")
print(L)
print("--------------------------------------------")
print(U)
print("--------------------------------------------")
print(np.dot(L,U))


[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
--------------------------------------------
[[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]]
--------------------------------------------
[[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]
--------------------------------------------
[[ 4.  3. -1.]
 [ 3.  5.  3.]
 [ 1.  1.  1.]]
[[1, 1, 1], [4, 3, -1], [3, 5, 3]]


In [24]:
P_inv = np.linalg.inv(P)
P_inv

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [25]:
Y_new = np.dot(P_inv,Y)
Y_new

array([6., 4., 1.])

In [26]:
L_inv = np.linalg.inv(L)
L_inv

array([[ 1.        ,  0.        ,  0.        ],
       [-0.75      ,  1.        ,  0.        ],
       [-0.18181818, -0.09090909,  1.        ]])

In [28]:
M = np.dot(L_inv,Y_new)
M

array([ 6.        , -0.5       , -0.45454545])

In [29]:
U_inv = np.linalg.inv(U)
U_inv

array([[ 0.25      , -0.27272727,  1.4       ],
       [ 0.        ,  0.36363636, -1.5       ],
       [ 0.        ,  0.        ,  1.1       ]])

In [30]:
X = np.dot(U_inv,M)
X

array([ 1. ,  0.5, -0.5])

In [31]:
###################################################3

### Apply the Jacobi and Gauss-Seidel method to solve
- 𝟓𝒙𝟏−𝟐𝒙𝟐+𝟑𝒙𝟑=−𝟏, −𝟑𝒙𝟏+𝟗𝒙𝟐+𝒙𝟑=𝟐, 𝟐𝒙𝟏−𝒙𝟐−𝟕𝒙𝟑=𝟑
- Solve once without vectorization then use vectorize implementation.
- Check for convergance.
- Use different tolerence and see the difference between the two methods. e.g. tol: 0.01,0.001,0.0001 ... etc.

In [72]:
A = np.array([[5, -2, 3],
             [-3, 9, 1],
             [2, -1, -7]])

B = [-1,2,3]

In [58]:
A = np.array([[5, -2, 3],
             [-3, 9, 1],
             [2, -1, -7]])
    
print(abs(np.diag(A)))
#print(np.fliplr(A).diagonal())

[5 9 7]


In [59]:
## Jacobi Not Vectorized

In [115]:
f1 = lambda x1,x2,x3: (2*x2 - 3*x3 -1)/5
f2 = lambda x1,x2,x3: (3*x1 - x3 +2)/9
f3 = lambda x1,x2,x3: (-2*x1 + x2 + 3)/-7

x1_0 = 0
x2_0 = 0
x3_0 = 0
count = 1
epsilon = 0.00001
condition = True

while condition:
    x1 = f1(x1_0,x2_0,x3_0)
    x2 = f2(x1_0,x2_0,x3_0)
    x3 = f3(x1_0,x2_0,x3_0)
    print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,x2,x3))
    e1 = abs(x1_0-x1);
    e2 = abs(x2_0-x2);
    e3 = abs(x3_0-x3);
    e_total = np.linalg.norm([e1,e2,e3])
    count += 1
    x1_0 = x1
    x2_0 = x2
    x3_0 = x3
    
    condition = e_total>epsilon 



1	-0.2000	0.2222	-0.4286

2	0.1460	0.2032	-0.5175

3	0.1917	0.3284	-0.4159

4	0.1809	0.3323	-0.4207

5	0.1854	0.3293	-0.4244

6	0.1863	0.3312	-0.4226

7	0.1861	0.3313	-0.4226

8	0.1861	0.3312	-0.4227

9	0.1861	0.3312	-0.4227

10	0.1861	0.3312	-0.4227



In [61]:
## Gauss-Seidel Not Vectorized

In [116]:
f1 = lambda x1,x2,x3: (2*x2 - 3*x3 -1)/5
f2 = lambda x1,x2,x3: (3*x1 - x3 +2)/9
f3 = lambda x1,x2,x3: (-2*x1 + x2 + 3)/-7

x1_0 = 0
x2_0 = 0
x3_0 = 0
count = 1
epsilon = 0.00001
condition = True

while condition:
    x1 = f1(x1_0,x2_0,x3_0)
    x2 = f2(x1,x2_0,x3_0)
    x3 = f3(x1,x2,x3_0)
    print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,x2,x3))
    e1 = abs(x1_0-x1);
    e2 = abs(x2_0-x2);
    e3 = abs(x3_0-x3);
    e_total = np.linalg.norm([e1,e2,e3])
    count += 1
    x1_0 = x1
    x2_0 = x2
    x3_0 = x3
    
    condition = e_total>epsilon 


1	-0.2000	0.1556	-0.5079

2	0.1670	0.3343	-0.4286

3	0.1909	0.3335	-0.4217

4	0.1864	0.3312	-0.4226

5	0.1861	0.3312	-0.4227

6	0.1861	0.3312	-0.4227

7	0.1861	0.3312	-0.4227



In [111]:
## Jacobi Vectorized
D = np.diag(np.diag(A))
U = np.triu(A,k=1)*-1
L = np.tril(A,k=-1)*-1
x = [0,0,0]
print(D)
print("--------------------")
print(L)
print("--------------------")
print(U)
print("--------------------")
print(x)
print("--------------------")

T = np.dot(sp.linalg.inv(D),(L+U))
C = np.dot(sp.linalg.inv(D),B)
condition = True
while condition:
    x_0 = x
    x = np.dot(T,x) + C
    if np.abs(x-x_0).max() < epsilon:
        condition = False
    print(x)

[[ 5  0  0]
 [ 0  9  0]
 [ 0  0 -7]]
--------------------
[[ 0  0  0]
 [ 3  0  0]
 [-2  1  0]]
--------------------
[[ 0  2 -3]
 [ 0  0 -1]
 [ 0  0  0]]
--------------------
[0, 0, 0]
--------------------
[[-0.2        -0.2        -0.2       ]
 [ 0.22222222  0.22222222  0.22222222]
 [-0.42857143 -0.42857143 -0.42857143]]
[[ 0.14603175  0.14603175  0.14603175]
 [ 0.2031746   0.2031746   0.2031746 ]
 [-0.51746032 -0.51746032 -0.51746032]]
[[ 0.19174603  0.19174603  0.19174603]
 [ 0.32839506  0.32839506  0.32839506]
 [-0.41587302 -0.41587302 -0.41587302]]
[[ 0.18088183  0.18088183  0.18088183]
 [ 0.33234568  0.33234568  0.33234568]
 [-0.42070043 -0.42070043 -0.42070043]]
[[ 0.18535853  0.18535853  0.18535853]
 [ 0.32926066  0.32926066  0.32926066]
 [-0.42436886 -0.42436886 -0.42436886]]
[[ 0.18632558  0.18632558  0.18632558]
 [ 0.33116049  0.33116049  0.33116049]
 [-0.42264909 -0.42264909 -0.42264909]]
[[ 0.18605365  0.18605365  0.18605365]
 [ 0.33129176  0.33129176  0.33129176]
 [-0.4226

In [113]:
## Gauss-Seidel Vectorized
A = np.array([[5, -2, 3],
             [-3, 9, 1],
             [2, -1, -7]])

B = np.array([[-1]
              ,[2]
              ,[3]])
D = np.diag(np.diag(A))
U = (np.triu(A)-D)*-1
L = (np.tril(A)-D)*-1
x = np.array([[0]
              ,[0]
              ,[0]])
print(D)
print("--------------------")
print(L)
print("--------------------")
print(U)
print("--------------------")
print(x)
print("--------------------")

T = np.dot(np.linalg.inv((D-L)),U)
C = np.dot(np.linalg.inv((D-L)),B)
condition = True
while condition:
    x_0 = x
    x = np.dot(T,x) + C
    if np.abs(x-x_0).max() < epsilon:
        condition = False
    print(x[0],x[1],x[2]) 

[[ 5  0  0]
 [ 0  9  0]
 [ 0  0 -7]]
--------------------
[[ 0  0  0]
 [ 3  0  0]
 [-2  1  0]]
--------------------
[[ 0  2 -3]
 [ 0  0 -1]
 [ 0  0  0]]
--------------------
[[0]
 [0]
 [0]]
--------------------
[-0.2] [0.15555556] [-0.50793651]
[0.16698413] [0.33432099] [-0.42862182]
[0.19090149] [0.3334807] [-0.42166825]
[0.18639323] [0.33120533] [-0.42263127]
[0.18606089] [0.33120155] [-0.42272568]
[0.18611603] [0.33123042] [-0.42271405]
[0.1861206] [0.33123065] [-0.42271278]


### Use np.linalg.solve() to solve the previous system and compare the results.

In [97]:
np.linalg.solve(A,B)

array([ 0.18611987,  0.33123028, -0.42271293])

### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

In [99]:
P,L,U = sp.linalg.lu(A)
print(P)
print("--------------------------------------------")
print(L)
print("--------------------------------------------")
print(U)
print("--------------------------------------------")
print(np.dot(L,U))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------------------------------
[[ 1.          0.          0.        ]
 [-0.6         1.          0.        ]
 [ 0.4        -0.02564103  1.        ]]
--------------------------------------------
[[ 5.         -2.          3.        ]
 [ 0.          7.8         2.8       ]
 [ 0.          0.         -8.12820513]]
--------------------------------------------
[[ 5. -2.  3.]
 [-3.  9.  1.]
 [ 2. -1. -7.]]


In [100]:
P_inv = np.linalg.inv(P)
P_inv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
L_inv = np.linalg.inv(L)
L_inv

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.6       ,  1.        ,  0.        ],
       [-0.38461538,  0.02564103,  1.        ]])

In [103]:
M = np.dot(L_inv,B)
M

array([-1.        ,  1.4       ,  3.43589744])

In [104]:
U_inv = np.linalg.inv(U)
U_inv

array([[ 0.2       ,  0.05128205,  0.09148265],
       [ 0.        ,  0.12820513,  0.04416404],
       [-0.        , -0.        , -0.12302839]])

In [105]:
X = np.dot(U_inv,M)
X

array([ 0.18611987,  0.33123028, -0.42271293])